services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - INTEGRATION_TEST=1
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer

  balancer:
    # Для тестів включаємо режим відлагодження, коли балансувальник додає інформацію, кому було відправлено запит.
    command: ["lb", "--trace=true"]
